import AuthProvider from "@/components/AuthProvider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CUB Chat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"bg-[url('/login-bg.jpeg')] " + inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
        </body>
    </html>
  );
}
